language: go

go:
  - 1.9

services:
  - rabbitmq

before_install: go get -t ./...
script: go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
